apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-prod
  namespace: argocd
spec:
  source:
    repoURL: https://github.com/AhmadShaaban1/cloud-native-ecommerce.git
    targetRevision: v1.0.4  # Use tags for prod
    path: k8s/overlays/prod
  destination:
    server: https://production-cluster
    namespace: production